name: LEECO 1S

on:
  push:
    branches: [ "stock_5.8.017s" ]
  pull_request:
    branches: [ "stock_5.8.017s" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
